apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lattix-service.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "lattix-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: lattix
