rootProject.name = "lattix"

// Add Java modules as they are implemented, for example:
// include("gateway:api-gateway")
// include("services:workspace-service")
include("shared:backend")
include("shared:tracing")
include("shared:events")
include("shared:persistence")
include("shared:test")
include("shared:integration-test")
include("gateway:api-gateway")
include("services:auth-service")
include("services:user-service")
include("services:workspace-service")
include("services:repository-service")
include("services:project-service")
include("services:notification-service")
include("services:tool-service")
include("services:search-service")
include("services:knowledge-service")
include("services:memory-service")
include("services:document-service")
include("services:analytics-service")
include("services:logging-service")
include("services:monitoring-service")
include("services:_template")
