apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lattix-worker.fullname" . }}
  labels:
    app: {{ include "lattix-worker.name" . }}
    chart: {{ include "lattix-worker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "lattix-worker.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "lattix-worker.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "lattix-worker.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: {{ quote $value }}
{{- end }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 6 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 6 }}
      affinity: {{ toYaml .Values.affinity | nindent 6 }}
