replicaCount: 1
image:
  repository: lattix/worker
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
nodeSelector: {}
tolerations: []
affinity: {}
env: {}
secrets: {}
