apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repository-cache-template
  namespace: services
  labels:
    lattix.io/template: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: lattix-gp3
