apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-pdb
  namespace: gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: lattix
      lattix.io/component: gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: services-default-pdb
  namespace: services
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: lattix
