apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/namespace.yaml
  - external-secrets/namespace.yaml
  - istio/namespace.yaml
  - keda/namespace.yaml
  - vpa/namespace.yaml
